baseURL = "https://kastyshyn.com/"
languageCode = "en-us"
title = "Gene Kastyshyn"
theme = "ananke"

[params]
  description = "AI/ML, engineering, agentic systems"

[caches]
  [caches.images]
    dir = ':cacheDir/images'